apiVersion: v1
kind: Service
metadata:
  name: jenkins-instance
  namespace: jenkins-instance
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: master
  selector:
    app: master
  type: NodePort
