apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-discovery
  namespace: jenkins
spec:
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 3838
      targetPort: 3838
      name: slaves